Started on Drag and Drop
Interactive-Design-and-Technology/interactive-learning pull request #23
Opened 2023-04-17 15:28 UTC by Anmol135

Drag and Drop from Anmol

2023-04-17 20:47 UTC, Anmol135 commented
Just updated the code with some changes that follow the actual drag and drop rule.

2023-04-17 20:47 UTC, Anmol135 commented
Still need to work on checking the right answers but I think I have the base down.

2023-04-18 19:04 UTC, Anmol135 commented
The validation part has been done and we have some styling done to the page.

2023-04-18 20:47 UTC, Anmol135 commented
The project is almost done still need to figure out a way to reset answers.

2023-04-18 21:06 UTC, FeXd commented
Screenshot for future reference:

![image](https://user-images.githubusercontent.com/553767/232905072-1c3b90ef-43cc-42b2-9a60-a395b1f7eac0.png)

2023-04-18 21:11 UTC, FeXd requested changes
Overall the functionality of the code is good, I would just like to see some cleanup with indentation and commented out code deleted. Good work.

2023-04-18 21:11 UTC, FeXd commented on drag_and_drop/index.html
> +	<!-- <button>Check</button> -->
Some weird indentation in this file, and a comment that can be deleted.

2023-04-18 21:11 UTC, FeXd commented on drag_and_drop/main.js
> +        // document.getElementById("demo").innerHTML = "Started to drag the p element.";
Be sure to remove commented out code that isn't used anymore.

2023-04-18 21:11 UTC, FeXd commented on drag_and_drop/main.js
> +        // document.getElementById("demo").innerHTML = "Finished dragging the p element.";
Same as above comment, removed commented out code.

2023-04-18 21:11 UTC, FeXd commented on drag_and_drop/main.js
> +// function showDetails(animal) {
Remove commented out function.

2023-04-19 15:09 UTC, Anmol135 commented
Fixed Indentation Issues and took out the commented functions.

2023-04-19 15:10 UTC, FeXd approved these changes

2023-04-19 15:11 UTC, merged